### ISSUE TITLE
dead writes in DC_Measure_short

### ISSUE THREAD

**Issue by rdewaele** [istepura/kw41z-rf-driver#1]
The static analyser mentioned dead writes on these lines:

https://github.com/istepura/kw41z-rf-driver/blob/aa97c05719edc4937a9a67e6b4aa640703461bee/source/xcvr/fsl_xcvr_trim.c#L308-L309

But I am not sure what the intent is of these sum_ variables: the iteration count is 1 so their value is effectively the same as the non-sum variables. Is this for debug purposes?

**Comment by istepura** [comment]
Just like the file from #2 this one was also taken from KW41 SDK. I agree with you, code does not make much sense, except for debugging. 

If you're considering using this driver for your purposes, be advised - it is very far from being production quality and I don't plan to support/maintain this project in foreseeable future, so feel free to fork and do what you think needs to be done.

**Comment by rdewaele** [comment]
Thanks again!
