### ISSUE TITLE
common config: initialized field overwritten

### ISSUE THREAD

**Issue by rdewaele** [istepura/kw41z-rf-driver#2]
These two lines initialise the same property:

https://github.com/istepura/kw41z-rf-driver/blob/aa97c05719edc4937a9a67e6b4aa640703461bee/source/cfgs_kw4x_3x_2x/fsl_xcvr_common_config.c#L478-L479

Given the structure declaration, I think the second one should be `recycle_count_init_32mhz`? Is this correct and can the values be left unchanged?

**Comment by istepura** [comment]
I appreciate your interest in making the code better, but this file is part of NXP KW41Z SDK, which I got from https://mcuxpresso.nxp.com/. If you feel there's an issue with this code, you should really report it to NXP.

**Comment by rdewaele** [comment]
Oh okay, I was under the impression that this was the original code repository, as I got here via https://os.mbed.com/users/istepura/code/kw41z-rf-driver/

Thanks for the clarification, I will take my reports over there (i.e. nxp). ;-)
